[build-system]
build-backend = "uv_build"
requires = ["uv_build>=0.9.5,<0.10.0"]

[dependency-groups]
dev = [
  {include-group = "test"},
  "black>=23.3.0",
  "pre-commit>=4.3.0",
  "ruff>=0.0.261"
]
docs = [
  "ghp-import>=2.1.0",
  "ipython>=8.18.1",
  "ipywidgets>=8.1.8",
  "matplotlib>=3.9.4",
  "myst-nb>=1.3.0",
  "notebook>=7.5.6",
  "sphinx>=7.4.7",
  "sphinx-book-theme>=1.1.4",
  "sphinx-copybutton>=0.5.2",
  "sphinx-design>=0.6.1"
]
test = [
  "pytest>=8.4.2",
  "pytest-asyncio>=1.2.0",
  "pytest-xdist>=3.8.0"
]

[project]
authors = [
  {email = "ddegen@ethz.ch", name = "David Degen"}
]
classifiers = [
  "Programming Language :: Python :: 3"
]
dependencies = [
  "aiofiles",
  "astropy",
  "numpy",
  "pandas",
  "httpx",
  "tqdm"
]
description = "A Python package to interact with the Exoplanet Follow-up Observing Program (ExoFOP) database, providing tools for querying and analyzing exoplanet data, particularly light curves and time series data from missions like TESS."
keywords = ["astronomy", "astrophysics", "time series analysis", "lightcurves", "ExoFOP"]
license = {text = "MIT"}
name = "exofop"
readme = "README.md"
requires-python = ">=3.10"
version = '0.0.3'

[project.optional-dependencies]
all = ["lightkurve"]
visualization = ["ipython", "matplotlib", "notebook", "ipywidgets"]

[project.urls]
"Bug Tracker" = "https://github.com/dgegen/exofop/issues"
"Homepage" = "https://dgegen.github.io/exofop/"
"Source" = "https://github.com/dgegen/exofop"

[tool.ruff]
line-length = 100
lint.extend-select = [
  "C4", # Unnecessary generators
  "SIM", # SIMPLIFY
  "NPY", # #NumPy-specific rules
  "N", # pep8 Naming
  "RUF"
]
